### PR TITLE
Add starting new season function 

### PR DESCRIPTION
**Pull request by taipeicityeth**
passing all tests 

Screenshot 2023-05-08 at 11 22 37 AM

### CODE REVIEW

**Comment by audsssy** [comment]
Digging the simplicity of the call and le gas report. Re `seasonId` numbering, what do you thinking about  codifying it to increment by 1 per new season (e.g., season 1 for first season, season 2 for second season, and so on)? 

For example: 
Screenshot 2023-05-08 at 10 01 58

Asking because the current process allows admin to supply any `seasonId` so long as it is larger than `currentSeason`, which leaves the act of numbering `seasonId` to the front end, including etherscan. I'm not sure if this is desirable, and I see both ways to work so will defer to you good ser (will need to update test if we defer numbering to contract doe)!

**Comment by taipeicityeth** [comment]
@audsssy Hmm I usually lean towards leaving the contract as flexible as possible (without negative consequences) and trusting the human/front end calling the contract to have enough context to not set season 1 after season 2 haha 

if someone misses the season number, can always be reset back here, though I see your point, the setCurrentSeason feels more like a safety backdoor than what's necessarily needed

**Comment by audsssy** [comment]
Yea, makes sense. It is certainly more an edge case here, specifically anyone on the admin team can use etherscsan to set `seasonId` intentionally or unintentionally. But other than this, lgtm!

**Comment by taipeicityeth** [comment]
will merge this first so you can reference this @audsssy

**Pull request merged**
